version: '3'
services:
    php-apache:
        image: php:7.2.1-apache
        ports:
            - "80:80"
        volumes:
            - /home/rtorres/Documents/dev/prod/commercial-roof-calculator:/var/www/html
        links:
            - 'mysql'

    mysql:
        image: mysql:8
        container_name: mysql
        volumes:
            - mysql:/var/lib/mysql
        ports:
            -   "3306:3306"
        environment:
            MYSQL_ALLOW_EMPTY_PASSWORD: "no"
            MYSQL_ROOT_PASSWORD: "root"
#            MYSQL_USER: 'root'
#            MYSQL_PASSWORD: 'root'
            MYSQL_DATABASE: 'apilord'

    apilord:
        image: apilord:0.1v
        container_name: apilord
        ports:
            -   "8080:8080"
        depends_on:
            -   mysql

volumes:
    mysql:
    php-apache: